<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.addons.reactor.bundles</artifactId>
    <version>5.2.1</version>
  </parent>

  <artifactId>org.openhab.binding.balboa</artifactId>

  <name>openHAB Add-ons :: Bundles :: Balboa Binding</name>

  <build>
    <finalName>${project.artifactId}-${project.version}-${local.build.timestamp}</finalName>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>local-build-timestamp</id>
            <goals>
              <goal>timestamp-property</goal>
            </goals>
            <phase>validate</phase>
            <configuration>
              <name>local.build.timestamp</name>
              <pattern>yyyyMMdd-HHmmss</pattern>
              <timeZone>Europe/Berlin</timeZone>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
